config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'stories#welcome', as: 'home'

  get 'build' => 'stories#build_story'

  post '/feedback/', to: 'stories#add_feedback'

  resources :stories

  resources :verbs

  resources :object_or_types, only: [:new, :create, :update, :edit, :destroy]
end

app/models/story.rb
class Story < ApplicationRecord
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :check_user, only: [:edit, :update, :destroy]
  skip_before_action :verify_authenticity_token, only: :add_feedback

  def check_user
    @story = Story.find(params[:id])
    unless current_user.id == @story.user_id || current_user.admin
      redirect_to(@story, notice: 'You do not have permissions to make changes to this story')
    end
  end

  def add_feedback
    if (params[:add].length + params[:subtract].length == 0)
      render :json => {:success => 'false'}.to_json
    else
      params[:add].split(",").each do | verb_id |
        verb = Verb.find(verb_id)
        if verb.weight < 100
          verb.weight = verb.weight + 5
          verb.save
        end
      end

      params[:subtract].split(",").each do | verb_id |
        verb = Verb.find(verb_id)
        if verb.weight > 5
          verb.weight = verb.weight - 5
          verb.save
        end
      end

      render :json => {:success => 'true'}.to_json
    end
  end

  def index
    @stories = Story.all.order('created_at DESC')
  end

  def build_story
    @story = Story.new
    @random_characters = RandomCharacter.all
    @random_items = RandomItem.all
    @random_places = RandomPlace.all
  end

  def new
    # Source: http://rubyquiz.com/quiz96.html
    # Original Author: Boris Prinz
    # Changed by: Seth Conklin
    @story = Story.new
    @title = params[:title]
    @author = params[:author]

    @cast = Entities.new(Character) do |c|
      params[:name].zip(params[:gender]).each do |name, gender|
        c.create name, gender == 'female' ? :female : :male, 1
      end
    end

    @verbs = Verb.all

    @actions = Entities.new(Action) do |a|
      @verbs.each do |verb|
        objects_or_types = []
        verb.object_or_types.order([:order]).each do |object_or_type|
          objects_or_types << (object_or_type.class_or_string == 'class' ? Object.const_get(object_or_type.name) : object_or_type.name)
        end
        a.create verb.name, objects_or_types, verb.part, verb.weight, verb.id
      end

    end

    @items = Entities.new(Item) do |i|
      params[:item].each do |item|
        i.create item, 1
      end
    end

    @places = Entities.new(Place) do |p|
      params[:place].each do |place|
        p.create place, 1
      end
    end

    @bridges = Entities.new(Bridge) do |b|
      b.create '.', 5
      b.create ', because', 1
      b.create ', while', 1
      b.create '. Later', 1
      b.create '. Then', 1
      b.create '. The next day', 1
      b.create '. And so', 1
      b.create ', but', 1
      b.create '. Soon', 1
      b.create ', and', 1
      b.create ' until', 1
      b.create ' although', 1
    end

    @all = { Character => @cast,   Action => @actions,
            Place     => @places, Item   => @items }

    random_story = RandomStory.new(:cast => @cast, :actions => @actions,
                                    :items => @items, :places => @places,
                                    :bridges => @bridges, :all => @all)
    @story_text = random_story.to_s
    @verbs_used = random_story.verbs
  end

  def create
    @story = Story.new(story_params)

    if @story.save
      redirect_to @story
    else
      render 'new'
    end

  end

  def show
    @story = Story.find(params[:id])
  end

  def update
    @story = Story.find(params[:id])

    if @story.update(story_params)
      redirect_to @story
    else
      render 'edit'
    end
  end

  def edit
    @story = Story.find(params[:id])
  end

  def destroy
    @story = Story.find(params[:id])
    @story.destroy

    redirect_to stories_path
  end

  private

  def story_params
    params.require(:story).permit(:title,:author,:text,:user_id)
  end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_form.html.erb
<div class="container text-center">
  <%= simple_form_for @story do |f| %>
  <%= f.input :title, label_html: {class: "text-light"} %>
  <%= f.input :author, label_html: {class: "text-light"} %>
  <%= f.input :text, input_html: {rows: "8"}, label_html: {class: "text-light"} %>
  <%= f.input :user_id, input_html: {type: "hidden"}, label: false %>
  <%= f.button :submit, class: "btn-lg btn-light" %>
  <% end %>
</div>

app/views/stories/build_story.html.erb
<% content_for :create_class, "active" %>
<% content_for :page_title, "Build your story" %>
<div class="container text-left mb-5">
  <h4 class="text-light">Fill in the following fields, or click
    <button type="button" class="btn btn-light btn-lg"
    onclick="getRandomValues()">here</button>
    to randomly generate values</h4>
    <p class="lead bg-warning">Note: Story generation is random, and not
      everything entered is guaranteed to show up in the story</p>
  <%= simple_form_for(@story, as: :user, method: :get, url: new_story_path) do |f| %>
    <%= f.input :title, input_html: {name: "title"}, label_html: {class: "text-light"} %>
    <%= f.input :author, input_html: {name: "author"}, label_html: {class: "text-light"} %>
    <!-- Story Characters -->
    <h4 class="text-light mt-3">Characters</h4>
    <div class="form-group row" id="characters">
      <div class="col-sm-4">
        <label class="text-light">Name</label>
        <input class="form-control" type="text" name="name[]">
      </div>
      <div class="col-sm-2">
        <label class="text-light">Gender</label>
        <select class="form-control" name="gender[]">
          <option value="female" selected>Female</option>
          <option value="male">Male</option>
        </select>
      </div>
    </div>
    <button class="btn btn-light" type="button" onclick="addCharacter()"
    name="add" id="add_character">Add</button>
    <button class="btn btn-light" type="button" onclick="removeCharacter()"
    name="remove" id="remove_character">Remove</button>
    <!-- Story Items -->
    <h4 class="text-light mt-3">Items</h4>
    <div class="form-group row" id="items">
      <div class="col-sm-4">
        <label class="text-light">Item</label>
        <input class="form-control" type="text" name="item[]">
      </div>
    </div>
    <button class="btn btn-light" type="button" onclick="addValue('item')"
    name="add" id="add_item">Add</button>
    <button class="btn btn-light" type="button" onclick="removeValue('item')"
    name="remove" id="remove_item">Remove</button>
    <!-- Story Places -->
    <h4 class="text-light mt-3">Places</h4>
    <div class="form-group row" id="places">
      <div class="col-sm-4">
        <label class="text-light">Place</label>
        <input class="form-control" type="text" name="place[]">
      </div>
    </div>
    <button class="btn btn-light" type="button" onclick="addValue('place')"
    name="add" id="add_place">Add</button>
    <button class="btn btn-light" type="button" onclick="removeValue('place')"
    name="remove" id="remove_place">Remove</button>
    <br>
    <%= f.button :submit, "Build Story", class: "btn-lg btn-light mt-3" %>
  <% end %>
</div>
<script type="text/javascript" src="/js/build_story.js"></script>
<script type="text/javascript">
  // Fill in all of the current fields
  function getRandomValues() {
    var title = document.getElementById("user_title");
    var author = document.getElementById("user_author");
    var names = document.getElementsByName("name[]");
    var genders = document.getElementsByName("gender[]");
    var items = document.getElementsByName("item[]");
    var places = document.getElementsByName("place[]");
    var names_used = new Array(names.length);
    var items_used = new Array(items.length);
    var places_used = new Array(places.length);
    var character_array = <%= @random_characters.to_json.html_safe %>
    var item_array = <%= @random_items.to_json.html_safe %>
    var place_array = <%= @random_places.to_json.html_safe %>

    var i;
    var random;
    for (i = 0; i < names.length; i++) {
      random = rand(character_array.length);
      names[i].value = character_array[random].name;
      genders[i].value = character_array[random].gender;
    }

    for (i = 0; i < items.length; i++) {
      items[i].value = item_array[rand(item_array.length)].name;
    }

    for (i = 0; i < places.length; i++) {
      places[i].value = place_array[rand(place_array.length)].name;
    }

    author.value = character_array[rand(character_array.length)].name;
    switch(rand(6)) {
      case 0:
        title.value = 'The story of ' + names[rand(names.length)].value;
        break;
      case 1:
        title.value = 'Trouble in ' + places[rand(places.length)].value;
        break;
      case 2:
        title.value = 'The mystery of ' + items[rand(items.length)].value;
        break;
      case 3:
        title.value = names[rand(names.length)].value + ' goes to ' +
          places[rand(places.length)].value;
        break;
      case 4:
        title.value = names[rand(names.length)].value + ' and ' +
          items[rand(items.length)].value;
        break;
      case 5:
        title.value = items[rand(items.length)].value + ' in ' + places[rand(places.length)].value;
        break;
    }

  }
</script>

app/views/stories/edit.html.erb
<% content_for :page_title, "Edit story" %>

<%= render 'form' %>

app/views/stories/index.html.erb
<% content_for :view_class, "active" %>
<% content_for :page_title, "Story List" %>
<% @stories.each do |story| %>
  <div class="container bg-light text-left mt-2">
      <h3><%= link_to story.title, story %></h3>
      <h4>By <%= story.author %></h4>
      <p class="lead"><%= story.text %></p>
  </div>
<% end %>

app/views/stories/new.html.erb
<% content_for :page_title, "New Story" %>
<div class="container text-center">
  <button type="button" name="refresh" onclick="location.reload()"
  class="btn btn-light m-3">Retry</button>
  <%= simple_form_for @story do |f| %>
  <%= f.input :title, input_html: {value: @title}, label_html: {class: "text-light"} %>
  <%= f.input :author, input_html: {value: @author}, label_html: {class: "text-light"} %>
  <%= f.input :text, input_html: {rows: "8", value: @story_text}, label_html: {class: "text-light"} %>
  <%= f.input :user_id, input_html: {value: current_user.id, type: "hidden"}, label: false %>
  <%= f.button :submit, "Save Story", class: "btn btn-lg btn-light" %>
  <% end %>
  <button type="button" name="button" class="mt-2 btn btn-light" id="give_feedback" onclick="showFeedback()">Give Feedback</button>
  <button type="button" name="button" class="d-none" id="hide_feedback" onclick="hideFeedback()">Hide Feedback</button>
  <div class="d-none" id="feedback">
    <h3>Sentences Used</h3>
    <% @verbs_used.zip(0..@verbs_used.length).each do |verb, i| %>
      <div class="row">
        <div class="col-6 text-left ">
          Character
          <%= Verb.find(verb).name %>
          <% Verb.find(verb).object_or_types.each do |object_or_type| %>
            <%= object_or_type.name %>
          <% end %>
        </div>
        <div class="col-2">
          Dislike <input type="radio" name="verb[<%= i %>]" value="<%= verb %>">
        </div>
        <div class="col-2">
          Neutral <input type="radio" name="verb[<%= i %>]" value="<%= verb %>" checked>
        </div>
        <div class="col-2">
          Like <input type="radio" name="verb[<%= i %>]" value="<%= verb %>">
        </div>
      </div>
    <% end %>
    <button type="button" name="button" onclick="submitFeedback()" class="btn btn-secondary mt-2">Submit Feedback</button>
  </div>
</div>
<script type="text/javascript" src="/js/new_story.js"></script>

app/views/stories/show.html.erb
<% content_for :page_title, @story.title %>
<div class="container text-center bg-light pt-1 pb-1">
  <h2>By <%= @story.author %></h2>
  <p class="lead"><%= @story.text %></p>
  <% if current_user.id == @story.user_id || current_user.admin %>
    <%= link_to "Edit", edit_story_path(@story), class: "btn btn-secondary" %>
    <%= link_to "Delete", story_path(@story), method: :delete, data: {confirm: "Are you sure? "}, class: "btn btn-danger" %>
  <% end %>
</div>

app/views/stories/welcome.html.erb
<% content_for :home_class, "active" %>
<% content_for :page_title, "Welcome to Story Builder" %>
<div class="container text-center">
  <p class="lead text-light">
    Where the stories are made just for you.
  </p>
  <p class="lead">
    <%= link_to "Create Story", build_path, :class => "btn btn-lg btn-light" %>
  </p>
  <img class="d-block w-100" src="images/magic-book.png" alt="Magic Book">
</div>