config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'stories#welcome', as: 'home'

  get 'build' => 'stories#build_story'

  post '/feedback/', to: 'stories#add_feedback'

  resources :stories

  resources :verbs

  resources :object_or_types, only: [:new, :create, :update, :edit, :destroy]
end

app/models/action.rb
# Source: http://rubyquiz.com/quiz96.html
# Author: Boris Prinz
# Changed by: Seth Conklin
class Action < Base
  constructor :name, :objects_or_types, :part, :weight, :verb_id
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/base.rb
# Source: http://rubyquiz.com/quiz96.html
# Original Author: Boris Prinz
# Changed by: Seth Conklin
class Base
  def self.constructor *args
    attr_accessor(*args)
    define_method :initialize do |*values|
      (0..(args.size - 1)).each do |i|
        self.instance_variable_set("@#{args[i]}", values[i])
      end
    end
  end

  def to_s
    @name
  end
end

app/models/bridge.rb
# Source: http://rubyquiz.com/quiz96.html
# Author: Boris Prinz
# Changed by: Seth Conklin
class Bridge < Base
  constructor :name, :weight
end

app/models/character.rb
# Source: http://rubyquiz.com/quiz96.html
# Author: Boris Prinz
# Changed by: Seth Conklin
class Character < Base
  constructor :name, :gender, :weight
end

app/models/entities.rb
# Source: http://rubyquiz.com/quiz96.html
# Author: Boris Prinz
# Changed by: Seth Conklin
class Entities
  def initialize klass
    @entities = []
    @klass = klass
    yield(self)
  end

  def create *args
    @entities << @klass.new(*args)
  end

  def entities
    @entities
  end

  def entities=(entities)
    @entities = entities
  end

  def pick
    total_weight = 0
    @entities.each do | entity |
      total_weight += entity.weight
    end
    random_weight = rand(total_weight)
    current_weight = 0

    @entities.each do | entity |
      if random_weight >= current_weight && random_weight < current_weight + entity.weight
        return entity
      else
        current_weight += entity.weight
      end
    end
  end
end

app/models/item.rb
# Source: http://rubyquiz.com/quiz96.html
# Author: Boris Prinz
# Changed By: Seth Conklin
class Item < Base
  constructor :name, :weight
end

app/models/object_or_type.rb
class ObjectOrType < ApplicationRecord
  belongs_to :verb
end

app/models/place.rb
# Source: http://rubyquiz.com/quiz96.html
# Author: Boris Prinz
# Changed by: Seth Conklin
class Place < Base
  constructor :name, :weight
end

app/models/pronoun.rb
# Source: http://rubyquiz.com/quiz96.html
# Author: Boris Prinz
class Pronoun < PronounBase
  self.cases = ['she', 'he']
end

app/models/pronoun_base.rb
# Source: http://rubyquiz.com/quiz96.html
# Author: Boris Prinz
class PronounBase < Base
  constructor :gender
  class << self
    attr_accessor :cases
  end

  def to_s
    cases = self.class.cases
    @gender == :female ? cases[0] : cases[1]
  end
end

app/models/random_character.rb
class RandomCharacter < ApplicationRecord
end

app/models/random_item.rb
class RandomItem < ApplicationRecord
end

app/models/random_place.rb
class RandomPlace < ApplicationRecord
end

app/models/random_story.rb
# Source: http://rubyquiz.com/quiz96.html
# Original Author: Boris Prinz
# Changed by: Seth Conklin
require 'enumerator'

class RandomStory
  attr_reader :verbs

  def initialize (params = {})
    @sentences = []
    @bridges = params.fetch(:bridges)
    @verbs = []
    all_actions = params[:actions].entities

    # Divide the story into beginning, middle, and end
    params[:actions].entities = all_actions.select {|a| a.part == 'beginning'}
    add_sentences(params, 3)

    params[:actions].entities = all_actions.select {|a| a.part == 'middle'}
    add_sentences(params, 4)

    params[:actions].entities = all_actions.select {|a| a.part == 'end'}
    add_sentences(params, 3)

    combine_subjects
  end

  # Add anywhere from count to 2 x count sentences to the story using the
  # provided parameters
  def add_sentences(params, count)
    1.upto(rand(count)+count) do
      new_sentence = Sentence.new(params)
      while (@sentences.include? new_sentence) do
        new_sentence = Sentence.new(params)
      end
      unless @verbs.include? new_sentence.verb.verb_id
        @verbs << new_sentence.verb.verb_id
      end
      @sentences << new_sentence
    end
  end

  # When the last sentece had the same subject, replace subject with
  # 'he' or 'she'
  def combine_subjects
    @sentences.each_cons(2) do |s1, s2|
      if s1.subject == s2.subject
        s2.subject = Pronoun.new(s1.subject.gender)
      end
    end
  end

  # combine sentences to a story:
  def to_s
    text = 'Once upon a time ' + @sentences[0].to_s
    @sentences[1..-1].each do |sentence|
      bridge = @bridges.pick.to_s
      text += bridge + ' ' +
              ( bridge[-1,1] == '.' ? sentence.to_s.capitalize :
                                      sentence.to_s )
      end
      text.gsub!(/ ,/, ',') # a little clean-up
      text += ". The End."
    end
  end

app/models/reflexive_pronoun.rb
# Source: http://rubyquiz.com/quiz96.html
# Author: Boris Prinz
class ReflexivePronoun < PronounBase
  self.cases = ['herself', 'himself']
end

app/models/sentence.rb
# Source: http://rubyquiz.com/quiz96.html
# Original Author: Boris Prinz
# Changed by: Seth Conklin
class Sentence
  attr_accessor :subject
  attr_reader :verb, :objects

  def initialize (params = {})
    @subject = params.fetch(:cast).pick
    @verb = params.fetch(:actions).pick
    @objects = []
    @verb.objects_or_types.each do |obj_or_type|
      if String === obj_or_type
        @objects << obj_or_type
      else
        if obj_or_type == PossessiveAdjective or
          obj_or_type == ReflexivePronoun or
          obj_or_type == Pronoun
          @objects << obj_or_type.new(@subject.gender)
        else
          thingy = params.fetch(:all)[obj_or_type].pick
          if thingy == @subject
            thingy = ReflexivePronoun.new(thingy.gender)
          end
          @objects << thingy
        end
      end
    end
  end

  def == (new_sentence)
    self.to_s == new_sentence.to_s
  end

  def to_s
    [@subject, @verb, @objects].flatten.map{|e| e.to_s}.join(' ')
  end
end

app/models/story.rb
class Story < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/verb.rb
class Verb < ApplicationRecord
  has_many :object_or_types, dependent: :destroy
end

app/controllers/verbs_controller.rb
class VerbsController < ApplicationController
  before_action :authenticate_user!, :check_admin

  def check_admin
    unless current_user.admin
      redirect_to '/'
    end
  end

  def index
    @verbs = Verb.all.order("part, created_at")
  end

  def new
    @verb = Verb.new
  end

  def create
    @verb = Verb.new(verb_params)

    if @verb.save
      @verb.reload
      if params[:object_name]
        params[:object_name].zip(params[:class_or_string], params[:object_order]).each do |name, class_or_string, order|
          @verb.object_or_types.create(name: name, class_or_string: class_or_string, order: order)
        end
      end
      redirect_to @verb
    else
      render 'new'
    end

  end

  def show
    @verb = Verb.find(params[:id])
  end

  def update
    @verb = Verb.find(params[:id])

    if @verb.update(verb_params)
      redirect_to @verb
    else
      render 'edit'
    end
  end

  def edit
    @verb = Verb.find(params[:id])
  end

  def destroy
    @verb = Verb.find(params[:id])
    @verb.destroy

    redirect_to verbs_path
  end

  private

  def verb_params
    params.require(:verb).permit(:name,:part)
  end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/verbs_helper.rb
module VerbsHelper
end

app/views/verbs/edit.html.erb
<% content_for :home_class, "nav_item" %>
<% content_for :create_class, "nav_item" %>
<% content_for :view_class, "nav_item" %>
<% content_for :verb_class, "nav_item" %>
<% content_for :page_title, "Edit Verb" %>
<div class="container text-center">
  <%= simple_form_for @verb do |f| %>
  <%= f.input :name, label_html: {class: "text-light"} %>
  <%= f.input :part, collection: [['Beginning', 'beginning'],
  ['Middle', 'middle'], ['End', 'end']],
  prompt: "Choose the story part", label_html: {class: "text-light"} %>
  <input type="hidden" name="verb_id" id="verb_id" value="<%= @verb.id %>">
  <div class="row">
    <% @verb.object_or_types.order([:order]).each do |object_or_type| %>
      <div class="col-sm-3">
        <p class="lead text-light"><u><%= object_or_type.class_or_string.capitalize %></u></p>
        <p class="lead text-light"><%= object_or_type.name %></p>
        <%= link_to "Edit", edit_object_or_type_path(object_or_type), class: "btn btn-light" %>
        <%= link_to "Delete", object_or_type_path(object_or_type), method: :delete, data: {confirm: "Are you sure? "}, class: "btn btn-danger" %>
      </div>
    <% end %>
    <div class="col-sm-3">
        <%= link_to "New Object or Type", new_object_or_type_path(verb_id: @verb.id), class: "btn btn-light" %>
    </div>
  </div>
  <%= f.button :submit, class: "btn-lg btn-light" %>
  <% end %>
</div>

app/views/verbs/index.html.erb
<% content_for :home_class, "nav_item" %>
<% content_for :create_class, "nav_item" %>
<% content_for :view_class, "nav_item" %>
<% content_for :verb_class, "nav_item active" %>
<% content_for :page_title, "Verb Index" %>
<div class="container">
  <%= link_to "New Verb", new_verb_path, class: "btn btn-light" %>
  <h2 class="text-light text-center">Beginning</h2>
  <% @verbs.where(part: 'beginning').each do |verb| %>
    <div class="row bg-light text-left mt-2">
      <div class="col-sm-3">
        <h3><u>Verb</u></h3>
        <h3><%= link_to verb.name, verb %></h3>
      </div>
      <% verb.object_or_types.order([:order]).each do |object_or_type| %>
        <div class="col-sm-3">
          <h3><u><%= object_or_type.class_or_string.capitalize %></u></h3>
          <h3><%= object_or_type.name %></h3>
        </div>
      <% end %>
    </div>
  <% end %>
  <h2 class="text-light text-center">Middle</h2>
  <% @verbs.where(part: 'middle').each do |verb| %>
    <div class="row bg-light text-left mt-2">
      <div class="col-sm-3">
        <h3><u>Verb</u></h3>
        <h3><%= link_to verb.name, verb %></h3>
      </div>
      <% verb.object_or_types.order([:order]).each do |object_or_type| %>
        <div class="col-sm-3">
          <h3><u><%= object_or_type.class_or_string.capitalize %></u></h3>
          <h3><%= object_or_type.name %></h3>
        </div>
      <% end %>
    </div>
  <% end %>
  <h2 class="text-light text-center">End</h2>
  <% @verbs.where(part: 'end').each do |verb| %>
    <div class="row bg-light text-left mt-2">
      <div class="col-sm-3">
        <h3><u>Verb</u></h3>
        <h3><%= link_to verb.name, verb %></h3>
      </div>
      <% verb.object_or_types.order([:order]).each do |object_or_type| %>
        <div class="col-sm-3">
          <h3><u><%= object_or_type.class_or_string.capitalize %></u></h3>
          <h3><%= object_or_type.name %></h3>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/verbs/new.html.erb
<% content_for :home_class, "nav_item" %>
<% content_for :create_class, "nav_item" %>
<% content_for :view_class, "nav_item" %>
<% content_for :verb_class, "nav_item" %>
<% content_for :page_title, "New Verb" %>
<div class="container text-center">
  <%= simple_form_for @verb do |f| %>
  <%= f.input :name, label_html: {class: "text-light"} %>
  <%= f.input :part, collection: [['Beginning', 'beginning'],
  ['Middle', 'middle'], ['End', 'end']],
  prompt: "Choose the story part", label_html: {class: "text-light"} %>
  <button type="button" name="addObject" class="btn btn-light"
  onclick="addObjectOrType()">Add Object</button>
  <button id="remove_object" type="button" name="addObject" class="btn btn-light"
  onclick="removeObjectOrType()">Remove Object</button>
  <div class="form-group row" id="objects_or_types">
  </div>
  <%= f.button :submit, class: "btn-lg btn-light" %>
  <% end %>
</div>
<script type="text/javascript" src="/js/new_verb.js"></script>

app/views/verbs/show.html.erb
<% content_for :home_class, "nav_item" %>
<% content_for :create_class, "nav_item" %>
<% content_for :view_class, "nav_item" %>
<% content_for :verb_class, "nav_item" %>
<% content_for :page_title, "Verb" %>
<div class="container mt-2 p-3 bg-light text-center">
  <div class="row">
    <div class="col-sm-3">
      <h3><u>Story Part</u></h3>
      <h3><%= @verb.part %></h3>
    </div>
    <div class="col-sm-3">
      <h3><u>Verb</u></h3>
      <h3><%= @verb.name %></h3>
    </div>
      <% @verb.object_or_types.order([:order]).each do |object_or_type| %>
        <div class="col-sm-3">
          <h3><u><%= object_or_type.class_or_string.capitalize %></u></h3>
          <h3><%= object_or_type.name %></h3>
        </div>
      <% end %>
  </div>
  <%= link_to "Edit", edit_verb_path(@verb), class: "btn btn-secondary" %>
  <%= link_to "Delete", verb_path(@verb), method: :delete, data: {confirm: "Are you sure? "}, class: "btn btn-danger" %>
</div>