config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'stories#welcome', as: 'home'

  get 'build' => 'stories#build_story'

  post '/feedback/', to: 'stories#add_feedback'

  resources :stories

  resources :verbs

  resources :object_or_types, only: [:new, :create, :update, :edit, :destroy]
end

app/models/action.rb
# Source: http://rubyquiz.com/quiz96.html
# Author: Boris Prinz
# Changed by: Seth Conklin
class Action < Base
  constructor :name, :objects_or_types, :part, :weight, :verb_id
end

app/models/base.rb
# Source: http://rubyquiz.com/quiz96.html
# Original Author: Boris Prinz
# Changed by: Seth Conklin
class Base
  def self.constructor *args
    attr_accessor(*args)
    define_method :initialize do |*values|
      (0..(args.size - 1)).each do |i|
        self.instance_variable_set("@#{args[i]}", values[i])
      end
    end
  end

  def to_s
    @name
  end
end

app/models/bridge.rb
# Source: http://rubyquiz.com/quiz96.html
# Author: Boris Prinz
# Changed by: Seth Conklin
class Bridge < Base
  constructor :name, :weight
end

app/models/character.rb
# Source: http://rubyquiz.com/quiz96.html
# Author: Boris Prinz
# Changed by: Seth Conklin
class Character < Base
  constructor :name, :gender, :weight
end

app/models/entities.rb
# Source: http://rubyquiz.com/quiz96.html
# Author: Boris Prinz
# Changed by: Seth Conklin
class Entities
  def initialize klass
    @entities = []
    @klass = klass
    yield(self)
  end

  def create *args
    @entities << @klass.new(*args)
  end

  def entities
    @entities
  end

  def entities=(entities)
    @entities = entities
  end

  def pick
    total_weight = 0
    @entities.each do | entity |
      total_weight += entity.weight
    end
    random_weight = rand(total_weight)
    current_weight = 0

    @entities.each do | entity |
      if random_weight >= current_weight && random_weight < current_weight + entity.weight
        return entity
      else
        current_weight += entity.weight
      end
    end
  end
end

app/models/item.rb
# Source: http://rubyquiz.com/quiz96.html
# Author: Boris Prinz
# Changed By: Seth Conklin
class Item < Base
  constructor :name, :weight
end

app/models/object_or_type.rb
class ObjectOrType < ApplicationRecord
  belongs_to :verb
end

app/models/place.rb
# Source: http://rubyquiz.com/quiz96.html
# Author: Boris Prinz
# Changed by: Seth Conklin
class Place < Base
  constructor :name, :weight
end

app/models/pronoun.rb
# Source: http://rubyquiz.com/quiz96.html
# Author: Boris Prinz
class Pronoun < PronounBase
  self.cases = ['she', 'he']
end

app/models/pronoun_base.rb
# Source: http://rubyquiz.com/quiz96.html
# Author: Boris Prinz
class PronounBase < Base
  constructor :gender
  class << self
    attr_accessor :cases
  end

  def to_s
    cases = self.class.cases
    @gender == :female ? cases[0] : cases[1]
  end
end

app/models/random_character.rb
class RandomCharacter < ApplicationRecord
end

app/models/random_item.rb
class RandomItem < ApplicationRecord
end

app/models/random_place.rb
class RandomPlace < ApplicationRecord
end

app/models/random_story.rb
# Source: http://rubyquiz.com/quiz96.html
# Original Author: Boris Prinz
# Changed by: Seth Conklin
require 'enumerator'

class RandomStory
  attr_reader :verbs

  def initialize (params = {})
    @sentences = []
    @bridges = params.fetch(:bridges)
    @verbs = []
    all_actions = params[:actions].entities

    # Divide the story into beginning, middle, and end
    params[:actions].entities = all_actions.select {|a| a.part == 'beginning'}
    add_sentences(params, 3)

    params[:actions].entities = all_actions.select {|a| a.part == 'middle'}
    add_sentences(params, 4)

    params[:actions].entities = all_actions.select {|a| a.part == 'end'}
    add_sentences(params, 3)

    combine_subjects
  end

  # Add anywhere from count to 2 x count sentences to the story using the
  # provided parameters
  def add_sentences(params, count)
    1.upto(rand(count)+count) do
      new_sentence = Sentence.new(params)
      while (@sentences.include? new_sentence) do
        new_sentence = Sentence.new(params)
      end
      unless @verbs.include? new_sentence.verb.verb_id
        @verbs << new_sentence.verb.verb_id
      end
      @sentences << new_sentence
    end
  end

  # When the last sentece had the same subject, replace subject with
  # 'he' or 'she'
  def combine_subjects
    @sentences.each_cons(2) do |s1, s2|
      if s1.subject == s2.subject
        s2.subject = Pronoun.new(s1.subject.gender)
      end
    end
  end

  # combine sentences to a story:
  def to_s
    text = 'Once upon a time ' + @sentences[0].to_s
    @sentences[1..-1].each do |sentence|
      bridge = @bridges.pick.to_s
      text += bridge + ' ' +
              ( bridge[-1,1] == '.' ? sentence.to_s.capitalize :
                                      sentence.to_s )
      end
      text.gsub!(/ ,/, ',') # a little clean-up
      text += ". The End."
    end
  end

app/models/sentence.rb
# Source: http://rubyquiz.com/quiz96.html
# Original Author: Boris Prinz
# Changed by: Seth Conklin
class Sentence
  attr_accessor :subject
  attr_reader :verb, :objects

  def initialize (params = {})
    @subject = params.fetch(:cast).pick
    @verb = params.fetch(:actions).pick
    @objects = []
    @verb.objects_or_types.each do |obj_or_type|
      if String === obj_or_type
        @objects << obj_or_type
      else
        if obj_or_type == PossessiveAdjective or
          obj_or_type == ReflexivePronoun or
          obj_or_type == Pronoun
          @objects << obj_or_type.new(@subject.gender)
        else
          thingy = params.fetch(:all)[obj_or_type].pick
          if thingy == @subject
            thingy = ReflexivePronoun.new(thingy.gender)
          end
          @objects << thingy
        end
      end
    end
  end

  def == (new_sentence)
    self.to_s == new_sentence.to_s
  end

  def to_s
    [@subject, @verb, @objects].flatten.map{|e| e.to_s}.join(' ')
  end
end

app/models/story.rb
class Story < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/verb.rb
class Verb < ApplicationRecord
  has_many :object_or_types, dependent: :destroy
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/verbs_helper.rb
module VerbsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-100">
  <head>
    <title>StoryBuilder</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column h-100  bg-secondary">
    <header>
      <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <%= link_to "Story Builder", home_path, :class => "navbar-brand" %>
        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="navbar-collapse collapse" id="navbarCollapse">
          <ul class="navbar-nav">
            <li class="<%= yield :home_class %>">
              <%= link_to "Home", home_path, :class => "nav-link" %>
            </li>
            <li class="<%= yield :create_class %>">
              <%= link_to "Build Story", build_path, :class => "nav-link" %>
            </li>
            <li class="<%= yield :view_class %>">
              <%= link_to "View Stories", stories_path, :class => "nav-link" %>
            </li>
            <% if user_signed_in? && current_user.admin %>
            <li class="<%= yield :verb_class %>">
              <%= link_to "View Verbs", verbs_path, :class => "nav-link" %>
            </li>
            <% end %>
            <% if user_signed_in? %>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %></a>
                <div class="dropdown-menu">
                  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => "dropdown-item" %>
                  <%= link_to "Edit registration", edit_user_registration_path, :class => "dropdown-item" %>
                </div>
              </li>
            <% else %>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Login</a>
                <div class="dropdown-menu">
                  <%= link_to "Login", new_user_session_path, :class => "dropdown-item" %>
                  <%= link_to "Register", new_user_registration_path, :class => "dropdown-item" %>
                </div>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>

    <main role="main">
      <div class="container-fluid bg-dark mt-5 pb-3 mb-1 text-center">
        <h1 class="mt-5 text-light"><%= yield :page_title %></h1>
      </div>
      <% if alert %>
      <div class="alert alert-danger text-center">
        <span class="lead"><%= alert %></span>
      </div>
      <% end %>
      <% if notice %>
      <div class="alert alert-warning text-center">
        <span class="lead"><%= notice %></span>
      </div>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>